
apiVersion: v1
kind: Service
metadata:
  name: ntap-easy-rag-ollama-service
  namespace: ntap-easy-rag
spec:
  type: ClusterIP
  selector:
    name: ntap-easy-rag
  ports:
  - port: 80
    name: http
    targetPort: http
    protocol: TCP