---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vectordb-milvus
  namespace: chat-with-docs
data:
  default.yaml: |
    etcd:
      endpoints:
      - vectordb-etcd-0.vectordb-etcd-headless.chat-with-docs.svc.cluster.local:2379

    metastore:
      type: etcd

    minio:
      address: 10.0.0.154
      port: 80
      accessKeyID: FG6XL311C6KXCQB54VID
      secretAccessKey: f_Erdsf9X918ibcAEH3Hw6YB7_6VP1n5D1uc5_Th
      useSSL: false
      bucketName: milvus
      rootPath: file
      useIAM: false
      useVirtualHost: false

    mq:
      type: rocksmq

    messageQueue: rocksmq

    rootCoord:
      address: localhost
      port: 53100
      enableActiveStandby: false  # Enable rootcoord active-standby

    proxy:
      port: 19530
      internalPort: 19529

    queryCoord:
      address: localhost
      port: 19531

      enableActiveStandby: false  # Enable querycoord active-standby

    queryNode:
      port: 21123
      enableDisk: true # Enable querynode load disk index, and search on disk index

    indexCoord:
      address: localhost
      port: 31000
      enableActiveStandby: false  # Enable indexcoord active-standby

    indexNode:
      port: 21121
      enableDisk: true # Enable index node build disk vector index

    dataCoord:
      address: localhost
      port: 13333
      enableActiveStandby: false  # Enable datacoord active-standby

    dataNode:
      port: 21124

    log:
      level: info
      file:
        rootPath: ""
        maxSize: 300
        maxAge: 10
        maxBackups: 20
      format: text
  user.yaml: |-
    #    For example enable rest http for milvus proxy
    #    proxy:
    #      http:
    #        enabled: true
    ##  Enable tlsMode and set the tls cert and key
    #  tls:
    #    serverPemPath: /etc/milvus/certs/tls.crt
    #    serverKeyPath: /etc/milvus/certs/tls.key
    #   common:
    #     security:
    #       tlsMode: 1
    common:
      security:
        authorizationEnabled: true