---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vectordb-milvus
  namespace: chat-with-docs
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: vectordb
spec:
  storageClassName: trident-fsx-nas
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "50Gi"