---
apiVersion: v1
kind: Service
metadata:
  name: vectordb-milvus
  namespace: chat-with-docs
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: vectordb
    app.kubernetes.io/version: "2.4.12"
    component: "standalone"
spec:
  type: ClusterIP
  ports:
    - name: milvus
      port: 19530
      protocol: TCP
      targetPort: milvus
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: metrics
  selector:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: vectordb
    component: "standalone"