---
apiVersion: v1
kind: Service
metadata:
  name: vectordb-etcd
  namespace: chat-with-docs
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: vectordb
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: "client"
      port: 2379
      targetPort: client
      nodePort: null
    - name: "peer"
      port: 2380
      targetPort: peer
      nodePort: null
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: vectordb