---
apiVersion: v1
kind: Service
metadata:
  name: vectordb-etcd-headless
  namespace: chat-with-docs
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: vectordb
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: "client"
      port: 2379
      targetPort: client
    - name: "peer"
      port: 2380
      targetPort: peer
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: vectordb